hash_function: dte_stand.hash_function.WeightedDxHashFunction
algorithm: dte_stand.algorithm.MateAlgorithm
path_calculator: dte_stand.paths.DAGCalculator
phi: dte_stand.phi_calculator.PhiCalculator.calculate_phi

lsdb_period: 30000
iterations: 50
plot_period: 50

log_path: ./experiment.log
log_level: DEBUG

debug_check_cycles: 0

store_hashweights: 0
store_nexthops: 0

mate:
  horizons: 30
  episodes: 100
  gamma: 0.9
  gae_lambda: 0.95
  reward: phi
  reward_computation: change
  min_weight: 1.0
  max_weight: 1.0
  greedy_epsilon: 0.5
  actions:
    addition:
      action: true
      value: 1
    subtraction:
      action: false
      value: 1
    multiplication:
      action: true
      value: 1.2
    division:
      action: true
      value: 1.2
    zero:
      action: false
      value: 0
