hash_function: dte_stand.hash_function.two_flow_test.TwoFlowTestHash
algorithm: dte_stand.algorithm.MateAlgorithm
path_calculator: dte_stand.paths.DAGCalculator
phi: dte_stand.phi_calculator.PhiCalculator.calculate_phi

lsdb_period: 30000
iterations: 1
plot_period: 50

log_path: ./experiment.log
log_level: DEBUG

debug_check_cycles: 0

store_hashweights: 0
store_nexthops: 0

mate:
  horizons: 45
  episodes: 1000
  gamma: 0.95
  gae_lambda: 0.95
  reward: fixed
  reward_computation: value
  min_weight: 1.0
  max_weight: 1.0
  greedy_epsilon: 1.0
  message_iterations: 2
  actions:
    addition:
      action: true
      value: 1
    subtraction:
      action: false
      value: 1
    multiplication:
      action: false
      value: 1.4
    division:
      action: false
      value: 1.4
    zero:
      action: true
      value: 0
